project: "Object_Classification_&_Detection"
hardware: "Red_Pitaya_FIUS"

dataset:
  input_size: 2048
  # Increased samples_per_file to reflect your high-density data collection
  samples_per_file: 400
  # Ensure the order matches the Class Weights in train.py exactly
  classes: ["Wall", "Person", "Chair", "Backpack", "Plant", "BigTable"]
  use_dummy: false 
  # NEW: Add a normalization flag to make the pipeline clear
  normalization: "max_abs" 

paths:
  raw_dir: "./data/binary/"
  processed_dir: "./data/processed/"
  model_output: "./models/fius_cnn_v1.pth"

training:
  batch_size: 16         # Stable gradients for 6 classes
  epochs: 150            # Keep this high
  learning_rate: 0.00005 # Lower to stop the F1-score from bouncing
  weight_decay: 0.001    # Prevent overfitting to the "Chair" class